### ISSUE TITLE
support bar for two monitors

### ISSUE THREAD

**Issue by DJeovannyZ** [jx11r/qtile#2]
hello, can yo help me?, i would like to add the bar on the second monitor, thanks in andvance

**Comment by jx11r** [comment]
sure, do you want the bar on both monitors?

**Comment by DJeovannyZ** [comment]
ya lo solvente, estuve moviendo las configuraciones y pude agregar la barra en ambos monitores.

**Comment by DJeovannyZ** [comment]
I already solved it, I was playing the settings and I was able to add the bar to a second monitor.
