### ISSUE TITLE
Arch Update Broke Config.

### ISSUE THREAD

**Issue by DJeovannyZ** [jx11r/qtile#3]
Hello, after last arch Update, the config has been broken.
The problem is with qtile-extras-git 
Python does not import qtile_extras.
Any Solution? 
I search information on the network, but the problem is new.
Thanks in Advance.

**Comment by jx11r** [comment]
Hi, you should reinstall qtile-git and qtile-extras:
```
yay -S qtile-git qtile-extras-git --answerclean All --noconfirm
```
